api = "0.2"

[buildpack]
id = "org.cloudfoundry.nodejs-compat"
name = "Node.js Compat Buildpack"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
